### ISSUE TITLE
Remove img/forum-topic.png image and replace with glyphicon or font-awesome icon

### ISSUE THREAD

**Issue by tigerclaw-az** [tigerclaw-az/NannyTracker#42]

**Comment by jakekh** [comment]
please everyone always use font-awesome

**Comment by lsf273** [comment]
Mkay, deal

On Tuesday, July 29, 2014, Jakekh notifications@github.com wrote:

> please everyone always use font-awesome
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ejwaibel/NannyTracker/issues/42#issuecomment-50549176
> .

## 

Logan Fetter
Web Content Manager
4MOST LLC.

t:   602.703.0045
w:  480. 427.4023
e:  LoganFetter62@gmail.com
